apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}-service
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.api.ports | toYaml | nindent 4 }}
