apiVersion: v1
kind: ConfigMap
metadata:
  name: verifier2-web-config
data:
  _features.conf : |
    enabledFeatures = []
  web.conf: |
    webHost = "0.0.0.0"
    webPort = 3000
  verifier-service.conf: |
    clientId: "verifier2"
    clientMetadata: {}
    urlPrefix: "https://verifier2.demo.walt.id/verification-session"
    baseUrl = "https://verifier2.demo.walt.id"
    urlHost: "openid4vp://authorize"
    key: {"type":"jwk","jwk":{"kty":"EC","d":"AEb4k1BeTR9xt2NxYZggdzkFLLUkhyyWvyUOq3qSiwA","crv":"P-256","kid":"_nd-T2YRYLSmuKkJZlRI641zrCIJLTpiHeqMwXuvdug","x":"G_TgBc0BkmMipiQ_6gkamIn3mmp7hcTrZuyrLTmknP0","y":"VkRMZdXYXSMff5AJLrnHiN0x5MV6u_8vrAcytGUe4z4"}}
    x5c: ["MIIBVzCB/aADAgECAggNKZAvUrtimzAKBggqhkjOPQQDAjAfMR0wGwYDVQQDDBR2ZXJpZmllci5leGFtcGxlLmNvbTAeFw0yNTEwMTQwNjI0MjBaFw0yNjEwMTQwNjI0MjBaMB8xHTAbBgNVBAMMFHZlcmlmaWVyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEG/TgBc0BkmMipiQ/6gkamIn3mmp7hcTrZuyrLTmknP1WRExl1dhdIx9/kAkuuceI3THkxXq7/y+sBzK0ZR7jPqMjMCEwHwYDVR0RBBgwFoIUdmVyaWZpZXIuZXhhbXBsZS5jb20wCgYIKoZIzj0EAwIDSQAwRgIhAOu0RGM6BjVQUepeLBogw+ZD3MQ9vFppbPIGMPjtn/qdAiEAttfdfyXHfzJ2tr+Pczyckzv3NlM43461cvP96sIzOQA="]
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: verifier2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verifier2
  template:
    metadata:
      labels:
        app: verifier2
      annotations:
        deployment/id: "_DEFAULT_DEPLOYMENT_"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: verifier2
          args:
            - "-l"
            - "trace"
          image: waltid/verifier-api2:__DEFAULT_IMAGE_TAG__
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: verifier2-web-config
              mountPath: "/waltid-verifier-api2/config/"
              readOnly: true
            - name: verifier-request-signing
              mountPath: "/waltid-verifier-api2/request-signing-secret/"
          ports:
            - containerPort: 3000
              name: http-api
      volumes:
        - name: verifier2-web-config
          configMap:
            name: verifier2-web-config
        - name: verifier-request-signing
          secret:
            secretName: verifier-request-signing
---
kind: Service
apiVersion: v1
metadata:
  name: verifier2
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
  selector:
    app: verifier2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verifier2
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - verifier2.demo.walt.id
      secretName: verifier2-tls-secret
  rules:
    - host: verifier2.demo.walt.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: verifier2
                port:
                  name: http
