apiVersion: v1
kind: Service
metadata:
  name: {{ include "issuer.fullname" . }}-service
  labels:
    {{- include "issuer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    {{ include "issuer.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.api.ports | toYaml | nindent 4 }}